### ISSUE TITLE
Question - Change Image from Onzu to jwetzell

### ISSUE THREAD

**Issue by ansred** [jwetzell/docker-guacamole#2]
Greetings,

Thanks for taking care of this image.

Just wanted to confirm, I have been using the old original image from Onzu. # https://github.com/oznu/docker-guacamole

Docker Compose.

```
version: '3.3'
services:
    guacamole:
        image: oznu/guacamole
        container_name: rds_guacamole_stack
        ports:
            - '8106:8080'
        volumes:
            - '/volume1/docker/containers/guacamole/stack:/config'
        environment:
            - 'EXTENSIONS=auth-duo'
```

Can I just simply replace the image in the compose:
FROM
        image: oznu/guacamole
TO 
        image: jwetzell/guacamole

And existing should work?

Thanks!
