### ISSUE TITLE
Raspberry Pi version still 1.4?

### ISSUE THREAD

**Issue by imc67** [jwetzell/docker-guacamole#20]
**Describe Your Problem:**
I use a docker-compose.yml with jwetzell/guacamole:arm32v7 but still get the 1.4.0 version of Guacamole instead of the latest.
What am I doing wrong?

**Logs:**

```

version: '3.8'
services:

  guacamole:
    hostname: guacamole
    image: jwetzell/guacamole:arm32v7
    ports:
      - 8080:8080
    volumes:
      - ./appdata/config:/config
    restart: unless-stopped

```

**Screenshots:**

**Environment:**

* **Guacamole Version**: latest
* **Operating System**:  Raspbian
