### ISSUE TITLE
Record video

### ISSUE THREAD

**Issue by netwaze** [jwetzell/docker-guacamole#31]
Hello,
I currently have a problem with your container image. Once deployed I put my connections and I activate the screen recording by putting a folder accessible by my container. 
I log in and I have log files in this folder, but when I log out and go to history I don't see a view button in log. 

If I ever need to make any changes, please let me know every step of the way. 

```
version: "3.9"
services:
  guacamole:
    container_name: Guacamole
    image: jwetzell/guacamole:latest
    healthcheck:
     test: curl -f http://localhost:8080/ || exit 1
    mem_limit: 6g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:false
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./guacamole:/config:rw
    environment:
      EXTENSIONS: history-recording-storage
```

Sincerely
