### ISSUE TITLE
Every change in the docker compose rebuilds the database and deletes settings

### ISSUE THREAD

**Issue by zackmuc** [jwetzell/docker-guacamole#47]
**Describe The Bug:**
When i rebuild the docker compose file the database is destroyed and new created

**To Reproduce:**

**Expected behavior:**
database should stay
**Logs:**

```
Remove any sensative information.
```

**Screenshots:**

```
**Environment:**
version: "3"
services:
  guacd:
    image: linuxserver/guacd
    container_name: guacd
    hostname: guacd
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/guacamole/drive:/drive:rw
      - /portainer/Files/AppData/Config/guacamole/record:/record:rw
    networks:
      - guacamole_network

  guacamole:
    image: jwetzell/guacamole:arm64
    container_name: guacamole
    hostname: guacamole
    restart: unless-stopped
    depends_on:
      - guacd
      - guacamole-db
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole-db
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: ***
      TOTP_ENABLED: 'true'
    links:
      - guacd
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-backend"
      - "traefik.http.routers.guacamole-secure.entrypoints=websecure"
      - "traefik.http.routers.guacamole-secure.rule=Host(`******)"
      #- "traefik.http.routers.guacamole-secure.middlewares=authelia@docker"
      #- "traefik.http.middlewares.guacamole-https.redirectscheme.scheme=https"
      #- "traefik.http.routers.guacamole.tls=true"
      #- "traefik.http.routers.guacamole.tls.certresolver=letsencrypt"
      #- "traefik.http.routers.guacamole.tls.domains[0].main=*.${DOMAIN}"
      #- "traefik.http.routers.guacamole.tls.options=myTLSOptions@file"
      - "traefik.http.routers.guacamole-secure.service=guacamole"
      #- "traefik.http.routers.guacamole.middlewares=guacamoleMdl"
      #- "traefik.http.middlewares.guacamoleMdl.addprefix.prefix=/guacamole"
      - "traefik.http.services.guacamole.loadBalancer.server.port=8080"

    networks:
      - guacamole_network
      - traefik-backend

  guacamole-db:
    image: mysql/mysql-server
    container_name: guacamole-db
    hostname: guacamole-db
    environment:
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: ***
      MYSQL_DATABASE: guacamole_db
    restart: unless-stopped
    volumes:
      #- /portainer/Files/AppData/Config/guacamole/initdb.sql:/initdb.sql				#DB configuration file
      - /portainer/Files/AppData/Config/guacamole/database:/var/lib/mysql/:rw
    networks:
      - guacamole_network

      
networks:
  traefik-backend:
    external:
      name: traefik-backend
  guacamole_network:
    external: false
```

```

CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
INSERT 0 1
INSERT 0 1
INSERT 0 6
INSERT 0 3
Starting guacamole client...
```
