### ISSUE TITLE
Docker Compose - External PostgreSQL

### ISSUE THREAD

**Issue by antwal** [jwetzell/docker-guacamole#60]
**Describe Your Problem:**
How use an external postgresql server?

this is not working, instead on the image guacamole/guacamole it works
```
    environment:
      POSTGRES_HOSTNAME: postgresql
      POSTGRES_DATABASE: guacamole
      POSTGRES_USER: user_guacamole
      POSTGRES_PASSWORD: user_password
```

**Comment by jwetzell** [comment]
This image is not compatible with the `guacamole/guacamole` image. You would likely have to dig in to the `guacamole.properties` file if you want to configure that.

**Comment by antwal** [comment]
I also tried with extensions but it doesn't work

```
  guacamole:
    hostname: guacamole
    container_name: guacamole
    restart: always
    image: jwetzell/guacamole
    ports:
      - "8080"
    volumes:
      - /mnt/storage/docker/guacamole/config:/config
    environment:
      - EXTENSIONS=auth-jdbc-postgresql
      - postgresql-hostname=postgresql
      - postgresql-database=guacamole_db
      - postgresql-username=guacamole_user
      - postgresql-password=password
```

on log i see:

```
[cont-init.d] 40-postgres.sh: exited 0.
[cont-init.d] 50-extensions.sh: executing... 
Cleaning Extensions from previous Guacamole versions
Cleaning Extensions
cp: cannot stat '/config/guacamole/extensions-available/guacamole-auth-jdbc-postgresql-1.5.5.jar': No such file or directory
[cont-init.d] 50-extensions.sh: exited 1.
[cont-init.d] done.
[services.d] starting services
Starting postgres...
Starting guacamole guacd...
/tmp:5432 - no response
Waiting for postgres to come up...
[services.d] done.
guacd[289]: INFO:	Guacamole proxy daemon (guacd) version 1.5.5 started
guacd[289]: INFO:	Listening on host 127.0.0.1, port 4822
LOG:  database system was shut down at 2025-01-24 15:30:59 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
/tmp:5432 - accepting connections
FATAL:  role "root" does not exist
...
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
Cleaning Extensions from previous Guacamole versions
Cleaning Extensions
cp: cannot stat '/config/guacamole/extensions-available/guacamole-auth-jdbc-postgresql-1.5.5.jar': No such file or directory
Starting guacamole client...
...
```

generated config
```
# cat guacamole/config/guacamole/guacamole.properties 
postgresql-hostname: localhost
postgresql-port: 5432
postgresql-database: guacamole_db
postgresql-username: guacamole
postgresql-password: null
```

what's wrong?
